name: wasm-build
on:
  push:
    branches: [ master ]
jobs:
  create:
    runs-on: ubuntu-latest
    container:
      image: emscripten/emsdk
    steps:
    - uses: actions/checkout@v2
    - name: 
      run: |
        make wasm
