name: wasm-build
on:
  push:
    branches: [ master ]
jobs:
  create:
    runs-on: ubuntu-latest
    container:
      image: emscripten/emsdk
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: make wasm
    - name: update
      run: |
        git fetch
        git checkout origin/pages
        cp build/js/* ./
        git add .
        git commit -m "beep boop"
        git push
